In [19]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix

In [20]:
X,y=make_classification(n_samples=1000,n_features=5,random_state=42)

In [21]:
X

array([[-0.43964281,  0.54254734, -0.82241993,  0.40136622, -0.85484   ],
       [ 2.82223116, -2.48085944, -1.14769139, -2.10113103,  3.04027792],
       [ 1.61838572, -1.36947785, -2.08411294, -1.17965857,  1.61360231],
       ...,
       [ 1.56038977, -0.22904063, -0.2344078 , -0.61957623, -1.10985576],
       [ 0.88692467, -0.22294581, -1.3088204 , -0.39617745, -0.40427827],
       [-2.74710392,  1.85043021, -0.19382614,  1.77741855, -1.58083381]])

In [22]:
y

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,

In [23]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=43)

In [24]:
X_train.shape

(700, 5)

In [25]:
X_test.shape

(300, 5)

In [26]:
model=LogisticRegression()

In [27]:
model

LogisticRegression()

In [28]:
#you are training your model here
model.fit(X_train,y_train)

LogisticRegression()

In [29]:
# predict the value
y_pred=model.predict(X_test)

In [30]:
accuracy_score(y_test,y_pred)

0.8833333333333333

In [31]:
confusion_matrix(y_test,y_pred)

array([[138,  12],
       [ 23, 127]], dtype=int64)

In [ ]:
overfitting mean
train accuracy is very good
and test accruacy is not

In [ ]:
underfitting means
train accuracy and test accuracy both are not good

In [32]:
model.score(X_train,y_train)

0.8542857142857143

In [ ]:
my model means my logistic regression is able to 85% data

In [33]:
0.8833333333333333-0.8542857142857143

0.02904761904761899

In [ ]:
# only 2% error , we consider my model is good.